CREATE TABLE IF NOT EXISTS sources (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    url VARCHAR(500) NOT NULL,
    username VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    sync_interval INT NOT NULL DEFAULT 1,
    last_sync DATETIME NULL,
    next_sync DATETIME NULL,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    enableproxy TINYINT(1) NOT NULL DEFAULT 0,
    disablestreamproxy TINYINT(1) NOT NULL DEFAULT 0,
    stream_follow_location TINYINT(1) NOT NULL DEFAULT 1,
    use_redirect TINYINT(1) NULL,
    use_redirect_xmltv TINYINT(1) NULL,
    enable_proxy BOOLEAN NOT NULL DEFAULT FALSE,
    enable_tunnel BOOLEAN NOT NULL DEFAULT FALSE,
    connect_xtream_api VARCHAR(20) NOT NULL DEFAULT 'DEFAULT',
    connect_xtream_stream VARCHAR(20) NOT NULL DEFAULT 'DEFAULT',
    connect_xmltv VARCHAR(20) NOT NULL DEFAULT 'DEFAULT',
    proxy_id INT NULL,
    black_list_filter LONGTEXT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_source_is_active (is_active),
    INDEX idx_source_next_sync (next_sync),
    INDEX idx_source_proxy_id (proxy_id),
    CONSTRAINT fk_source_proxy FOREIGN KEY (proxy_id) REFERENCES proxies(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
