CREATE TABLE IF NOT EXISTS clients (
    id INT AUTO_INCREMENT PRIMARY KEY,
    source_id INT NOT NULL,
    filter_id INT,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    name VARCHAR(255),
    email VARCHAR(255),
    expiry_date DATE,
    is_active TINYINT(1) NOT NULL DEFAULT 1,
    hide_adult_content TINYINT(1) NOT NULL DEFAULT 1,
    use_redirect TINYINT(1) NULL,
    use_redirect_xmltv TINYINT(1) NULL,
    enableproxy TINYINT(1) NULL,
    disablestreamproxy TINYINT(1) NULL,
    stream_follow_location TINYINT(1) NULL,
    enable_proxy BOOLEAN NULL,
    enable_tunnel BOOLEAN NULL,
    connect_xtream_api VARCHAR(20) NOT NULL DEFAULT 'INHERITED',
    connect_xtream_stream VARCHAR(20) NOT NULL DEFAULT 'INHERITED',
    connect_xmltv VARCHAR(20) NOT NULL DEFAULT 'INHERITED',
    max_connections INT NOT NULL DEFAULT 1,
    notes TEXT,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    last_login DATETIME NULL,
    FOREIGN KEY (source_id) REFERENCES sources(id) ON DELETE CASCADE,
    FOREIGN KEY (filter_id) REFERENCES filters(id) ON DELETE SET NULL,
    INDEX idx_client_source_is_active (source_id, is_active),
    INDEX idx_client_filter_id (filter_id),
    INDEX idx_client_expiry_date (expiry_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
