#SQLITE
quarkus.datasource.db-kind=other
quarkus.datasource.jdbc.driver=org.sqlite.JDBC
quarkus.datasource.jdbc.url=jdbc:sqlite:./db/app.sqlite
quarkus.datasource.username=
quarkus.datasource.password=
app.datasource.dialect=sqlite
